# Importig the library

In [1]:
import numpy as np  #it's a convention to use np. you can use your whatever you like

## N-Dimensional array - ndarray


We will generate an ndarray with np.arange method.

Syntax : np.arange([start,] stop[, step,], dtype=None)

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [5]:
np.arange(1,10, 3)

array([1, 4, 7])

In [6]:
np.arange(1,10, 2, dtype=np.float64)

array([ 1.,  3.,  5.,  7.,  9.])

### Examining ndrray

In [7]:
ds = np.arange(1,10,2)     ##(change data type to int32, itemsize will be 4 byte)
ds.ndim 

1

In [8]:
ds.shape

(5,)

In [12]:
ds.size

5

In [13]:
ds.dtype

#for more about data types - http://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html

dtype('int64')

In [14]:
ds.itemsize  #in bytes

8

In [15]:
ds

array([1, 3, 5, 7, 9])

In [16]:
# Memory Usage
ds.size * ds.itemsize

40

# Why to use numpy?

We can also use list to create array or matrix, then why should we use numpy?
We will compare the time it takes to create two lists and do some basic operations on them.

In [17]:
ar1 = np.array([1,2,3])
ar2 = np.array([3,4,5])
ar1 * ar2


array([ 3,  8, 15])

In [18]:

#normal python list
array1 = [1,2,3]
array2 = [3,4,5]

array1 * array2

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
np.array([1,2,3,4,5])

In [19]:
n = np.array([[1,2],[3,4],[5,6]])
n

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
n.shape

(3, 2)

In [21]:
print(n[1,1])
print(n[1][1])
print(n[1:3])

4
4
[[3 4]
 [5 6]]


### zeros, ones, full, eye, random, empty_like

In [22]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [23]:
np.zeros((3,4), dtype=np.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [25]:
np.full((2,2),3)

/root/anaconda3/lib/python3.5/site-packages/numpy/core/numeric.py:294: FutureWarning: in the future, full((2, 2), 3) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


array([[ 3.,  3.],
       [ 3.,  3.]])

In [26]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [ ]:
np.random.random(2) +1

In [ ]:
np.random.random((2,3)) 

In [ ]:
np.random.randint(2,5)

In [ ]:
np.random.randint(0,5,size=10)

In [ ]:
np.random.randint(0,5,size=(2,3))

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

In [ ]:
np.random.shuffle(a)
a

In [ ]:
np.random.seed(6)
np.random.random()

In [134]:
#np.random.seed(6)
np.random.random()

0.8928601514360016

In [ ]:
#for more - http://docs.scipy.org/doc/numpy/reference/routines.random.html

### np.linspace(start, stop, num=50, endpoint=True, retstep=False)

In [136]:
np.linspace(1,5)

array([ 1.        ,  1.08163265,  1.16326531,  1.24489796,  1.32653061,
        1.40816327,  1.48979592,  1.57142857,  1.65306122,  1.73469388,
        1.81632653,  1.89795918,  1.97959184,  2.06122449,  2.14285714,
        2.2244898 ,  2.30612245,  2.3877551 ,  2.46938776,  2.55102041,
        2.63265306,  2.71428571,  2.79591837,  2.87755102,  2.95918367,
        3.04081633,  3.12244898,  3.20408163,  3.28571429,  3.36734694,
        3.44897959,  3.53061224,  3.6122449 ,  3.69387755,  3.7755102 ,
        3.85714286,  3.93877551,  4.02040816,  4.10204082,  4.18367347,
        4.26530612,  4.34693878,  4.42857143,  4.51020408,  4.59183673,
        4.67346939,  4.75510204,  4.83673469,  4.91836735,  5.        ])

In [57]:
np.linspace(0,2,num=4)

array([ 0.        ,  0.66666667,  1.33333333,  2.        ])

In [137]:
np.linspace(0,2,num=4,endpoint=False)

array([ 0. ,  0.5,  1. ,  1.5])

In [138]:
a = np.linspace(0,2,num=4, retstep=True)
a

(array([ 0.        ,  0.66666667,  1.33333333,  2.        ]),
 0.6666666666666666)

# Array Math

In [23]:
x = np.array([[1,2,3],[5,6,7]])
y = np.array([[2,3,2],[4,9,1]])

print(x+y)
print(np.add(x,y))

[[ 3  5  5]
 [ 9 15  8]]
[[ 3  5  5]
 [ 9 15  8]]


In [24]:
print(x-y)
print(np.subtract(x,y))

[[-1 -1  1]
 [ 1 -3  6]]
[[-1 -1  1]
 [ 1 -3  6]]


In [29]:
print(x*y)
print(np.multiply(x,y))

[[ 2  6  6]
 [20 54  7]]
[[ 2  6  6]
 [20 54  7]]


In [30]:
print(x/y)
print(np.divide(x,y))

[[ 0.5         0.66666667  1.5       ]
 [ 1.25        0.66666667  7.        ]]
[[ 0.5         0.66666667  1.5       ]
 [ 1.25        0.66666667  7.        ]]


In [31]:
print(np.sqrt(x))

[[ 1.          1.41421356  1.73205081]
 [ 2.23606798  2.44948974  2.64575131]]


dot product

In [33]:
x = np.array([[1,2,3],[5,6,7],[3,4,5]])
y = np.array([[2,3,2],[4,9,1],[2,3,4]])
print(x.dot(y))
print(np.dot(x,y))

[[16 30 16]
 [48 90 44]
 [32 60 30]]
[[16 30 16]
 [48 90 44]
 [32 60 30]]


In [35]:
x.T

array([[1, 5, 3],
       [2, 6, 4],
       [3, 7, 5]])

## Statistical Analysis

In [39]:
data_set = np.random.random((2,3))
data_set

array([[ 0.52114864,  0.80253858,  0.02025404],
       [ 0.60993795,  0.43244568,  0.29840777]])

In [40]:
np.max(data_set)

0.80253858197092676

In [41]:
np.max(data_set, axis=0) #axis = 0 means column wise

array([ 0.60993795,  0.80253858,  0.29840777])

In [42]:
np.max(data_set, axis=1) #1 = row wise

array([ 0.80253858,  0.60993795])

In [43]:
np.min(data_set)

0.020254042768339642

In [44]:
np.mean(data_set)

0.44745544387712299

In [45]:
np.median(data_set)

0.47679716278344297

In [46]:
#standard deviation -for more details - https://en.wikipedia.org/wiki/Standard_deviation
np.std(data_set)

0.24591896590165616

In [47]:
np.sum(data_set)

2.684732663262738

In [51]:
np.sum(data_set, axis=1)

array([ 1.34394127,  1.34079139])

## Reshaping

### np.reshape(a, newshape, order='C')

In [151]:
print(data_set.shape)

(2, 3)


In [153]:
data_set.reshape(2,3)

array([[ 0.33197981,  0.82122912,  0.04169663],
       [ 0.10765668,  0.59505206,  0.52981736]])

In [154]:
np.reshape(data_set, (3,2))

array([[ 0.33197981,  0.82122912],
       [ 0.04169663,  0.10765668],
       [ 0.59505206,  0.52981736]])

In [155]:
np.reshape(data_set, (6,1))

array([[ 0.33197981],
       [ 0.82122912],
       [ 0.04169663],
       [ 0.10765668],
       [ 0.59505206],
       [ 0.52981736]])

In [156]:
np.reshape(data_set, (6))

array([ 0.33197981,  0.82122912,  0.04169663,  0.10765668,  0.59505206,
        0.52981736])

### np.ravel(a, order='C')

In [157]:
np.ravel(data_set)

array([ 0.33197981,  0.82122912,  0.04169663,  0.10765668,  0.59505206,
        0.52981736])

### Slicing

In [4]:
data_set = np.random.random((5,10))
data_set

array([[ 0.53874726,  0.02000632,  0.90900818,  0.36654297,  0.65134446,
         0.07980101,  0.92185212,  0.83322379,  0.5420978 ,  0.30692577],
       [ 0.13112531,  0.70075562,  0.64606504,  0.6299677 ,  0.91079496,
         0.70348807,  0.66712808,  0.36822904,  0.96871168,  0.55277265],
       [ 0.95361157,  0.51760599,  0.47326846,  0.70394865,  0.2123271 ,
         0.33939521,  0.92639101,  0.90796541,  0.92555159,  0.50204634],
       [ 0.83795441,  0.41737653,  0.67514267,  0.33050791,  0.81854706,
         0.11345362,  0.28641542,  0.20354031,  0.34033714,  0.90561553],
       [ 0.92983496,  0.77554688,  0.1555879 ,  0.58317963,  0.88873577,
         0.45779495,  0.78610215,  0.44005342,  0.11093259,  0.28123192]])

In [5]:
data_set[1]

array([ 0.13112531,  0.70075562,  0.64606504,  0.6299677 ,  0.91079496,
        0.70348807,  0.66712808,  0.36822904,  0.96871168,  0.55277265])

In [6]:
data_set[1][0]

0.13112530844280212

In [7]:
data_set[1,0]

0.13112530844280212

In [8]:
#slice in range
# data_set[row, column]


In [9]:
data_set[2:4]

array([[ 0.95361157,  0.51760599,  0.47326846,  0.70394865,  0.2123271 ,
         0.33939521,  0.92639101,  0.90796541,  0.92555159,  0.50204634],
       [ 0.83795441,  0.41737653,  0.67514267,  0.33050791,  0.81854706,
         0.11345362,  0.28641542,  0.20354031,  0.34033714,  0.90561553]])

In [10]:
data_set[2:4,0]

array([ 0.95361157,  0.83795441])

In [11]:
data_set[2:4,0:2]

array([[ 0.95361157,  0.51760599],
       [ 0.83795441,  0.41737653]])

In [12]:
data_set[:,0]

array([ 0.53874726,  0.13112531,  0.95361157,  0.83795441,  0.92983496])

#### Stepping

In [17]:
data_set[2:4:1] #it will select rows as per 2:4 and step will be 1

array([[ 0.95361157,  0.51760599,  0.47326846,  0.70394865,  0.2123271 ,
         0.33939521,  0.92639101,  0.90796541,  0.92555159,  0.50204634],
       [ 0.83795441,  0.41737653,  0.67514267,  0.33050791,  0.81854706,
         0.11345362,  0.28641542,  0.20354031,  0.34033714,  0.90561553]])

In [18]:
data_set[::]

array([[ 0.53874726,  0.02000632,  0.90900818,  0.36654297,  0.65134446,
         0.07980101,  0.92185212,  0.83322379,  0.5420978 ,  0.30692577],
       [ 0.13112531,  0.70075562,  0.64606504,  0.6299677 ,  0.91079496,
         0.70348807,  0.66712808,  0.36822904,  0.96871168,  0.55277265],
       [ 0.95361157,  0.51760599,  0.47326846,  0.70394865,  0.2123271 ,
         0.33939521,  0.92639101,  0.90796541,  0.92555159,  0.50204634],
       [ 0.83795441,  0.41737653,  0.67514267,  0.33050791,  0.81854706,
         0.11345362,  0.28641542,  0.20354031,  0.34033714,  0.90561553],
       [ 0.92983496,  0.77554688,  0.1555879 ,  0.58317963,  0.88873577,
         0.45779495,  0.78610215,  0.44005342,  0.11093259,  0.28123192]])

In [19]:
#step in rows
data_set[::2]

array([[ 0.53874726,  0.02000632,  0.90900818,  0.36654297,  0.65134446,
         0.07980101,  0.92185212,  0.83322379,  0.5420978 ,  0.30692577],
       [ 0.95361157,  0.51760599,  0.47326846,  0.70394865,  0.2123271 ,
         0.33939521,  0.92639101,  0.90796541,  0.92555159,  0.50204634],
       [ 0.92983496,  0.77554688,  0.1555879 ,  0.58317963,  0.88873577,
         0.45779495,  0.78610215,  0.44005342,  0.11093259,  0.28123192]])

In [20]:
data_set[2:4]

array([[ 0.95361157,  0.51760599,  0.47326846,  0.70394865,  0.2123271 ,
         0.33939521,  0.92639101,  0.90796541,  0.92555159,  0.50204634],
       [ 0.83795441,  0.41737653,  0.67514267,  0.33050791,  0.81854706,
         0.11345362,  0.28641542,  0.20354031,  0.34033714,  0.90561553]])

In [21]:
#step in columns
data_set[2:4,::2]

array([[ 0.95361157,  0.47326846,  0.2123271 ,  0.92639101,  0.92555159],
       [ 0.83795441,  0.67514267,  0.81854706,  0.28641542,  0.34033714]])